# Generated by Django 4.2.5 on 2023-11-08 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theapp', '0003_adddetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='adddetails',
        ),
    ]
