# Generated by Django 4.2.5 on 2023-11-08 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theapp', '0004_delete_adddetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='adddetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breweryName', models.CharField(max_length=100)),
                ('breweryAddress', models.CharField(max_length=100)),
                ('phoneNumber', models.CharField(max_length=100)),
                ('websiteURL', models.CharField(max_length=100)),
                ('currentRating', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
            ],
        ),
    ]
