# Generated by Django 4.2.5 on 2023-11-08 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theapp', '0005_adddetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='adddetails',
            new_name='add',
        ),
    ]
