# Generated by Django 4.2.5 on 2023-11-09 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theapp', '0006_rename_adddetails_add'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='add',
            new_name='detailsadd',
        ),
    ]
